/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eOS0spMkOXc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function HomePage() {
  return (
    <div className="flex min-h-screen">
      <aside className="w-64 bg-gray-100">
        <div className="bg-blue-700 text-white p-4">
          <h2>全部商品</h2>
        </div>
        <nav className="p-4 space-y-2">
          <a href="#" className="block text-gray-700">
            学习装备
          </a>
          <a href="#" className="block text-gray-700">
            营养膳食
          </a>
          <a href="#" className="block text-gray-700">
            学习攻坚
          </a>
          <a href="#" className="block text-gray-700">
            教育培训
          </a>
          <a href="#" className="block text-gray-700">
            健康五谷
          </a>
          <a href="#" className="block text-gray-700">
            精致生活
          </a>
          <a href="#" className="block text-gray-700">
            家居保卫
          </a>
          <a href="#" className="block text-gray-700">
            学习攻坚
          </a>
          <a href="#" className="block text-gray-700">
            校服文化
          </a>
        </nav>
      </aside>
      <main className="flex-1">
        <header className="bg-blue-500 text-white p-4 flex justify-around">
          <a href="#" className="font-bold">
            首页
          </a>
          <a href="#" className="font-bold">
            社区服务
          </a>
          <a href="#" className="font-bold">
            我的订单
          </a>
          <a href="#" className="font-bold">
            个人中心
          </a>
        </header>
        <div className="p-4 space-y-8">
          <section>
            <h2 className="text-xl font-bold">特产干货</h2>
            <div className="flex space-x-4 text-gray-700">
              <span>葡萄干</span>
              <span>白莲</span>
              <span>墨鱼</span>
              <span>菌菇</span>
              <span>桂圆</span>
              <span>银耳</span>
              <span>腐竹</span>
              <span>枸杞</span>
              <span>木耳</span>
            </div>
          </section>
          <section>
            <h2 className="text-xl font-bold">食用油</h2>
            <div className="flex space-x-4 text-gray-700">
              <span>茶油</span>
              <span>葵花油</span>
              <span>调和油</span>
              <span>菜籽油</span>
              <span>玉米油</span>
            </div>
          </section>
          <section>
            <h2 className="text-xl font-bold">米面</h2>
            <div className="flex space-x-4 text-gray-700">
              <span>米</span>
            </div>
          </section>
          <section>
            <h2 className="text-xl font-bold">粗粮</h2>
            <div className="flex space-x-4 text-gray-700">
              <span>绿豆</span>
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}
